// Generated by CoffeeScript 1.7.1
(function() {
  this.words = {};

  this.words.preset = "fucking demon baby antichrist fucking 60 year old 6 year old bowl cut looking ass bitch\nyou look like a dying old woman and a underage girl at the same damn time got a nigga fucked up";

  this.words.custom = "fucking {compound_adjective} {adjective} {noun} {noun} ass bitch\n{you} look like a {adjective} {noun} and a {noun} at the same {expletive} time you {expletive} {noun}\n{phrase} ass {noun}";

  this.words.expletive = "##########\nfucking\nmotherfucking\ndamn\ngoddamn\ngoddamned\ndamn fucking\ngoddamn fucking\ngoddamned fucking\ndamn motherfucking\ngoddamn motherfucking\ngoddamned motherfucking";

  this.words.intro = "######\nsup caleb\nsup cecil\nsup loli\nsup jwagzz\nsup jelly\nsup nig\nsup nick\nyou must be nick\nyou must be jwagzz\nhi troll\ngtfo\nplease die\ndie in a fire\nshut the fuck up\nnice try\ngo back to cc\ngo back to tc\ngo back to ilb\ngo lick loli's tampons\ngo eat some sleeping pills\ni can't believe you're this retarded\nyou can't fucking come to the meetup\ngo fuck yourself\nkill yourself\nare you fucking serious\neat a dick\nhurr durr\nnice b8\nnice reverse psychopathology\nhow fucking dare you\n1/10 cloxxies\ni hope kenny sits on you\nwhat a pathetic attempt\njesus fucking christ\nhow do you dress yourself\nreal fucking funny\nyou're projecting hard";

  this.words.you = "you\nyou\nyou\nyou\nyew";

  this.words.adjective = "####\nsad\nbeta\nomega\npathetic\nchildish\nprojecting\nautistic\nretarded\ndeluded\nforever alone\npsychotic\nobsessive\ntryhard\ndisgusting\nfat\ncurvy\ncreepy\n\"beautiful\"\nbutthurt\nbutt bitter\nanorexic\ncringeworthy\nembarrassing\nvapid\njewish\ncatty\njealous\nbitter\ninsufferable\nobnoxious\ndeaf\ndisgusting\nhuge\nyeasty\nultra mega\npitiful\ngross\nnarcissistic";

  this.words.compound_adjective = "####\nfat-ass\ncandy-ass\nfaggot-ass\ncactus-fucking\ntwo-faced\ndick-sucking\ndragon dildo-owning\nextra-water-retaining\npointy-kneed\nsharp-elbowed\nfake-titted\nfedora-wearing\ncum-guzzling\nass-kissing\nbutt-fucking\npotato-nosed\nroast-beef-vagina\ngilbert-gottfried-looking\nacne-covered";

  this.words.noun = "virgin\nneckbeard\npedo\njunefag\njunebot\nsperglord\naspie fuck\nburlap sack\npeterfag\ncuckold\ncatiebot\nstalker\ncunt\nbitch\npussy\njew\nfaggot\nfag\nson of a bitch\nnamefag\ntripfag\ndirectoryfag\nfeminazi\nattention whore\nhappy merchant\nkike\nhooknose\nhamplanet\nhamwhale\nshill\ncouncilfag\nfeminist\nholocaust believer\nfucking psycho\npsychopath\ntroll\ncaleb\ncecil 2.0\ntard\nturd\nturdface\nretard\nidiot\nretard idiot\nmoron\ndowny\nfaggot son\nsamefag\ndorito head\nshrimp\nforumfag\nautist\nembarrassment\nwhite knight\ndicknose\nbrony\nstrumpet\nhorsefucker\ngoblin\nfaggit\nfagget\nmlpfag\nshitfucker\nweeaboo\ngnome\ngarden gnome\ndumbfuck\nkitten stomper\ndaughter bather\nalpha beta\nshitlord\ntoad\nshitass\ngoy\nmale OC\nnigger frog\ninternet tough guy\ndingleberry\nbeta orbiter\nsociopath\ndemon baby antichrist\npsychotic autistic punk";

}).call(this);
