// Generated by CoffeeScript 1.7.1
(function() {
  this.words = {};

  this.words.intro = "sup caleb\nsup cecil\nsup loli\nsup jwagzz\nsup jelly\ngtfo\nplease die\ndie in a fire\ngo back to cc\ngo back to tc\ngo back to ilb\ngo eat some sleeping pills\ngo fuck yourself\nkill yourself\nhurr durr\nnice b8\nnice reverse psychopathology\nhow fucking dare you";

  this.words.you = "you\nyew";

  this.words.adjective = "sad\nbeta\nomega\npathetic\nchildish\nprojecting\nautistic\nretarded\ndeluded\nforever alone\npsychotic\nobsessive\ntryhard\ndisgusting\ncreepy\n\"beautiful\"\nbutthurt\nanorexic\ncringeworthy\nvapid\ncatty\njealous\ninsufferable\nobnoxious\ndeaf\ndisgusting\ngargantuan\nsupreme\nutter\nmassive\nultra\nmega\nultra mega\nmega ultra";

  this.words.compound_adjective = "fat-ass\ncandy-ass\nfaggot-ass\ncactus-fucking\ntwo-faced\ndick-sucking\ndragon dildo-owning\nextra-water-retaining\npointy-kneed\nsharp-elbowed\nfake-titted\nfedora-wearing\ncum-guzzling\nass-kissing\nbutt-fucking\npotato-nosed";

  this.words.noun = "virgin\nneckbeard\npedo\njunefag\njunebot\nsperglord\nfucking retard\naspie fuck\nburlap sack\npeterfag\ncuckold\ncatiebot\nstalker\ncunt\npussy\njew\nfaggot\nfag\nnamefag\ntripfag\nfeminazi\nattention whore\nhappy merchant\nkike\nhooknose\nshill\ncouncilfag\nfeminist\nholocaust believer\nfucking psycho\ntroll\ncaleb\ncecil 2.0\nretard\nfaggot son\nsamefag\nshrimp\nforumfag\nautist\nwhite knight\nbrony\nhorsefucker\nmlpfag\nweeaboo\ngnome\ndaughter bather\nshitlord\ntoad\ngoy\nmale OC";

}).call(this);
