// Generated by CoffeeScript 1.7.1
(function() {
  this.words = {};

  this.words.intro = "sup caleb\nsup cecil\nsup loli\nsup jwagzz\nsup jelly\nsup nig\nsup nick\ngtfo\nplease die\ndie in a fire\nshut the fuck up\nnice try\ngo back to cc\ngo back to tc\ngo back to ilb\ngo lick loli's tampons\ngo eat some sleeping pills\ni can't believe you're this retarded\ngo fuck yourself\nkill yourself\neat a dick\nhurr durr\nnice b8\nnice reverse psychopathology\nhow fucking dare you\n1/10 cloxxies\ni hope kenny sits on you";

  this.words.you = "you\nyew";

  this.words.adjective = "sad\nbeta\nomega\npathetic\nchildish\nprojecting\nautistic\nretarded\ndeluded\nforever alone\npsychotic\nobsessive\ntryhard\ndisgusting\nfat\ncurvy\ncreepy\n\"beautiful\"\nbutthurt\nanorexic\ncringeworthy\nembarrassing\nvapid\njewish\ncatty\njealous\ninsufferable\nobnoxious\ndeaf\ndisgusting\ngargantuan\nmassive\nyeasty\nultra mega\nmega ultra\npitiful\ngross";

  this.words.compound_adjective = "fat-ass\ncandy-ass\nfaggot-ass\ncactus-fucking\ntwo-faced\ndick-sucking\ndragon dildo-owning\nextra-water-retaining\npointy-kneed\nsharp-elbowed\nfake-titted\nfedora-wearing\ncum-guzzling\nass-kissing\nbutt-fucking\npotato-nosed\nroast-beef-vagina\ngilbert-gottfried-looking\nacne-covered";

  this.words.noun = "virgin\nneckbeard\npedo\njunefag\njunebot\nsperglord\nfucking retard\naspie fuck\nburlap sack\npeterfag\ncuckold\ncatiebot\nstalker\ncunt\npussy\njew\nfaggot\nfag\nnamefag\ntripfag\ndirectoryfag\nfeminazi\nattention whore\nhappy merchant\nkike\nhooknose\nhamplanet\nhamwhale\nshill\ncouncilfag\nfeminist\nholocaust believer\nfucking psycho\ntroll\ncaleb\ncecil 2.0\ntard\nturd\nturdface\nretard\nidiot\ndowny\nfaggot son\nsamefag\ndorito head\nshrimp\nforumfag\nautist\nembarrassment\nwhite knight\ndicknose\nbrony\nstrumpet\nhorsefucker\ngoblin\nmlpfag\nweeaboo\ngnome\nkitten stomper\ndaughter bather\nalpha beta\nshitlord\ntoad\ngoy\nmale OC\nnigger frog\ninternet tough guy\ndingleberry\nbeta orbiter";

}).call(this);
